- name: Montar /boot o /boot/efi para aplicar las actualizaciones
  ansible.builtin.include_tasks:
    file: montar_boot.yml

- name: Comprobar actualizaciones de seguridad
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    security: true
    update_cache: true
  register: actualizaciones
  notify:
    - 619B_Reiniciar_host

- name: Mostrar actualizaciones aplicadas
  ansible.builtin.include_tasks: aplicacion_de_actualizaciones_mostrar.yml
  when: actualizaciones.changed

- name: Desmontar /boot o /boot/efi después de aplicar las actualizaciones
  ansible.builtin.include_tasks:
    file: desmontar_boot.yml
