- name: Montar /boot o /boot/efi para aplicar las actualizaciones
  ansible.builtin.include_tasks:
    file: montar_boot.yml

- name: Comprobar actualizaciones de seguridad
  become: true
  ansible.builtin.dnf:
    name: '*'
    security: true
    state: latest
  register: actualizaciones
  notify: 
    - Mostrar_actualizaciones_aplicadas
    - Reiniciar_host

- name: Desmontar /boot o /boot/efi después de modificar la configuración de grub
  ansible.builtin.include_tasks:
    file: desmontar_boot.yml