- name: Crear banner
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    backup: true
  loop:
    - src: banner.j2
      dest: /etc/issue.net
    - src: banner.j2
      dest: /etc/issue
    - src: banner.j2
      dest: /etc/motd
