---
- name: Notificar contrase침a insegura de root
  ansible.builtin.debug:
    msg: "La contrase침a de root no est치 protegida con SHA-512"
  failed_when: true
  when: root_pass is not defined

- name: Forzar cambio de contrase침a de root
  become: true
  ansible.builtin.user:
    name: root
    password: "{{ root_pass | password_hash('sha512') }}"
  when: root_pass is defined

