---
- name: Configurar la caducidad de la clave de root
  become: true
  ansible.builtin.shell: |
    grep "root:[^:]*:[0-9]*:2:{{ PASS_MAX_DAYS }}:10:" /etc/shadow > /dev/null 2>&1
    if [ $? -eq 1 ]
    then
      /usr/bin/chage -m 2 -M {{ PASS_MAX_DAYS }} -W 10 root
      echo $?
    fi
  register: root_pass_change_params
  changed_when: root_pass_change_params.stdout == "0"
  notify:
    - Obtener_parametros_de_password_de_root

# A partir de ansible-core 2.16 se puede usar el m칩dulo user para configurar todos los par치metros de las claves de usuario
# - name: Configurar par치metros de caducidad de la clave de root
#   ansible.builtin.user:
#     name: root
#     password_expire_max: "{{ PASS_MAX_DAYS }}"
#     password_expire_min: 2
#     password_expire_warn: 10
#   notify:
#    - Obtener_parametros_de_password_de_root

- name: Comprobar si est치 caducada la password de root
  become: true
  ansible.builtin.shell: |
    test $(awk -F{{ ':' }} '$1 == "root" {print $3==""?"0":$3}' /etc/shadow) -ge $(( $(date +%s) / 86400 - {{ PASS_MAX_DAYS }} ))
  register: caducidad_password_de_root
  failed_when: false
  changed_when: caducidad_password_de_root.rc != 0
  notify:
    - Forzar_cambio_de_password_de_root
  check_mode: false
