- name: Comprobar si uefi está instalado
  ansible.builtin.stat:
    path: /sys/firmware/efi
  register: uefi

- name: Desmontar /boot
  become: true
  ansible.posix.mount:
    path: /boot
    state: unmounted
  changed_when: false
  when: not uefi.stat.exists
  check_mode: false

- name: Desmontar /boot/efi
  become: true
  ansible.posix.mount:
    path: /boot/efi
    state: unmounted
  changed_when: false
  when: uefi.stat.exists
  check_mode: false
