- name: Montar /boot o /boot/efi para modificar la configuración de grub
  ansible.builtin.include_tasks:
    file: montar_boot.yml

- name: Comprobar si la password de grub está configurada en grub (comprobación sacada de CLARA)
  become: true
  ansible.builtin.shell:
    cmd: grep -qi "root.*sha512" /etc/grub.d/40_custom
  register: configurar_password_de_root_en_grub
  failed_when: configurar_password_de_root_en_grub.stderr != ''
  changed_when: configurar_password_de_root_en_grub.rc != 0
  check_mode: false

- name: Configurar usuario y password de root en grub
  ansible.builtin.include_tasks: grub_configurar_password_de_root.yml
  when: configurar_password_de_root_en_grub.changed

- name: Permisos del fichero de configuración de grub
  become: true
  ansible.builtin.file:
    path: "/boot/grub2/grub.cfg"
    mode: '0600'
  when: not uefi.stat.exists

- name: Permisos del fichero de configuración de grub con UEFI
  become: true
  ansible.builtin.file:
    path: "/boot/efi/EFI/{{ ansible_distribution | lower }}/grub.cfg"
    mode: '0600'
  when: uefi.stat.exists

- name: Desmontar /boot o /boot/efi después de modificar la configuración de grub
  ansible.builtin.include_tasks:
    file: desmontar_boot.yml
