- name: Crear password de grub para root
  become: true
  ansible.builtin.expect:
    command: /bin/bash -c "grub2-mkpasswd-pbkdf2 | tee -a hash"
    responses:
      (?i)password|contraseña: "{{ grub_root_pass }}"
  register: hash_grub_root_pass
  check_mode: false

- name: Anadir el usuario root y su contraseña a superusers en grub
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/grub.d/40_custom
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^set superusers=', line: 'set superusers="root"' }
    - { regexp: '^password_pbkdf2 root', line: 'password_pbkdf2 root {{ (hash_grub_root_pass.stdout_lines | last).split(" ") | last }}' }
  register: password_de_root_configurada_en_grub

- name: Reconfigurar grub
  when: not uefi.stat.exists and password_de_root_configurada_en_grub.changed
  become: true
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  register: grub2_mkconfig_output
  changed_when: grub2_mkconfig_output.rc == 0

- name: Reconfigurar grub con UEFI
  when: uefi.stat.exists and password_de_root_configurada_en_grub.changed
  become: true
  ansible.builtin.command: grub2-mkconfig -o /boot/efi/EFI/{{ ansible_distribution | lower }}/grub.cfg
  register: grub2_mkconfig_uefi_output
  changed_when: grub2_mkconfig_uefi_output.rc == 0

