- name: Realizar copia de seguridad de los archivos de /etc/pam.d
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item }}"
    dest: "/etc/pam.d_backup/"
    mode: preserve
    backup: true
    local_follow: false
  with_fileglob:
    - /etc/pam.d/*

- name: Configurar pam_faillock.so
  become: true
  community.general.pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_deny.so
    state: after
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: "preauth silent audit deny=8 even_deny_root unlock_time=0"
  loop:
    - password-auth
    - system-auth

- name: Configurar pam_faillock.so para authfail
  become: true
  community.general.pamd:
    name: password-auth
    type: auth
    control: required
    module_path: pam_faillock.so
    state: after
    new_type: auth
    new_control: "[default=die]"
    new_module_path: pam_faillock.so
    module_arguments: "authfail deny=8 even_deny_root unlock_time=0"
  loop:
    - password-auth
    - system-auth

- name: Configurar pam_faillock.so para account
  become: true
  community.general.pamd:
    name: password-auth
    type: account
    control: required
    module_path: pam_unix.so
    state: after
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
  loop:
    - password-auth
    - system-auth

- name: Configurar pam_pwhistory.so
  become: true
  community.general.pamd:
    name: password-auth
    type: password
    control: required
    module_path: pam_deny.so
    state: after
    new_type: password
    new_control: requisite
    new_module_path: pam_pwhistory.so
    module_arguments: "debug use_authtok remember=25 retry=8"
  loop:
    - password-auth
    - system-auth

- name: Configurar pam_pwquality.so
  become: true
  community.general.pamd:
    name: password-auth
    type: password
    control: requisite
    module_path: pam_pwquality.so
    module_arguments: "try_first_pass local_users_only retry=3 authtok_type="
  loop:
    - password-auth
    - system-auth
