- name: Sistemas con categoría ENS básica
  tags:
    - ens_basica
  block:
    - name: CCN-STIC-619B-ENS_Paso1_contraseña_grub
      ansible.builtin.include_tasks: grub.yml

    - name: CCN-STIC-619B-ENS_Paso2_paquetes_huerfanos
      ansible.builtin.include_tasks: paquetes_huerfanos.yml

    - name: CCN-STIC-619B-ENS_Paso3_desinstalar_usuarios_innecesarios
      ansible.builtin.include_tasks: usuarios_innecesarios.yml

#    - name: CCN-STIC-619B-ENS_Paso4_limites_permisos_y_cad_contraseñas_B
#      vars:
#        - PASS_MAX_DAYS: 90
#        - PASS_MIN_LEN: 8
#      ansible.builtin.include_tasks: limites_permisos_y_cad_claves.yml

    # TODO: Terminar el Paso5
    - name: CCN-STIC-619B-ENS_Paso5_parametros_gnome
      ansible.builtin.debug:
        msg: "Este paso aún no ha sido implementado"

- name: Sistemas con categoría ENS media
  tags:
    - ens_media
  block:
    - name: CCN-STIC-619B-ENS_Paso1_contraseña_grub
      ansible.builtin.include_tasks: grub.yml

    - name: CCN-STIC-619B-ENS_Paso2_paquetes_huerfanos
      ansible.builtin.include_tasks: paquetes_huerfanos.yml

    - name: CCN-STIC-619B-ENS_Paso3_reglas_audit
      ansible.builtin.include_tasks: reglas_audit.yml

    - name: CCN-STIC-619B-ENS_Paso4_desinstalar_usuarios_innecesarios
      ansible.builtin.include_tasks: usuarios_innecesarios.yml

    - name: CCN-STIC-619B-ENS_Paso5_intentos_fallidos_M
      vars:
        - UNLOCK_TIME: 3600
      ansible.builtin.include_tasks: intentos_fallidos.yml

#    - name: CCN-STIC-619B-ENS_Paso6_limites_permisos_y_cad_contraseñas_M
#      vars:
#        - PASS_MAX_DAYS: 60
#        - PASS_MIN_LEN: 10
#      ansible.builtin.include_tasks: limites_permisos_y_cad_claves.yml

    # TODO: Terminar el Paso7
    - name: CCN-STIC-619B-ENS_Paso7_parametros_gnome
      ansible.builtin.debug:
        msg: "Este paso aún no ha sido implementado"

- name: Sistemas con categoría ENS alta
  tags:
    - ens_alta
  block:
    - name: CCN-STIC-619B-ENS_Paso1_contraseña_grub
      ansible.builtin.include_tasks: grub.yml

    - name: CCN-STIC-619B-ENS_Paso2_parametros_del_kernel
      ansible.builtin.include_tasks: parametros_del_kernel.yml

    - name: CCN-STIC-619B-ENS_Paso3_paquetes_huerfanos
      ansible.builtin.include_tasks: paquetes_huerfanos.yml

    - name: CCN-STIC-619B-ENS_Paso4_reglas_audit
      ansible.builtin.include_tasks: reglas_audit.yml

    - name: CCN-STIC-619B-ENS_Paso5_desinstalar_usuarios_innecesarios
      ansible.builtin.include_tasks: usuarios_innecesarios.yml

    - name: CCN-STIC-619B-ENS_Paso6_intentos_fallidos_A
      vars:
        - UNLOCK_TIME: 0
      ansible.builtin.include_tasks: intentos_fallidos.yml

#    - name: CCN-STIC-619B-ENS_Paso7_limites_permisos_y_cad_contraseñas_A
#      vars:
#        - PASS_MAX_DAYS: 45
#        - PASS_MIN_LEN: 12
#      ansible.builtin.include_tasks: limites_permisos_y_cad_claves.yml

    # TODO: Terminar el Paso8
    - name: CCN-STIC-619B-ENS_Paso8_parametros_gnome
      ansible.builtin.debug:
        msg: "Este paso aún no ha sido implementado"
