- name: Instalar yum-utils para trabajar
  become: true
  ansible.builtin.dnf:
    name: yum-utils
    state: present

- name: Eliminar paquetes instalados como dependencias que ya no son necesarios
  become: true
  ansible.builtin.dnf:
    autoremove: true

- name: Limpiar ficheros temporales de los repositorios
  become: true
  ansible.builtin.command: dnf clean all
  register: comando_output
  changed_when: comando_output.stdout | regex_search('^[1-9][0-9]*') and comando_output.rc == 0

- name: Buscar paquetes huérfanos
  ansible.builtin.command: "package-cleanup --orphans"
  register: paquetes_huerfanos
  changed_when: false
  check_mode: false

- name: Buscar paquetes que son dependencias sin uso (leaf nodes)
  ansible.builtin.command: "package-cleanup --leaves"
  register: paquetes_hoja
  changed_when: false
  check_mode: false

- name: Eliminar paquetes huerfanos y dependencias sin uso
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ paquetes_huerfanos.stdout | split }}"
    - "{{ paquetes_hoja.stdout | split }}"
