- name: Configuración de audit.rules
  become: true
  ansible.builtin.template:
    src: audit.rules.j2
    dest: "/etc/audit/rules.d/audit.rules"
    backup: true
    mode: '0600'
  register: reglas_audit_resultado
  notify:
    - Reiniciar_audit
- name: Configuración del fichero auditd.conf
  become: true
  ansible.builtin.replace:
    dest: /etc/audit/auditd.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
    backup: true
  loop:
    - { regexp: '^max_log_file\s*=\s*[0][0-9]*\s*$', line: "max_log_file = {{ max_log_file }}" }
    - { regexp: '^num_logs\s*=\s*[0][0-9]*\s*$', line: "num_logs = {{ num_logs }}" }
    - { regexp: '^max_log_file_action.*', line: "max_log_file_action = {{ max_log_file_action }}" }
  notify:
    - Reiniciar_audit
- name: Habilitar servicio auditd
  ansible.builtin.systemd:
    name: auditd
    enabled: true
