- name: Obtener lista de usuarios con UID = 0
  ansible.builtin.command: awk -F{{ ':' }} '$1 != "root" && $3 == 0 {print $1}' /etc/passwd
  register: users_uid0_list
  changed_when: users_uid0_list.stdout != ""
  notify: Mostrar_usuarios_con_uid0