- name: Obtener lista de usuarios sin contraseña
  become: true
  ansible.builtin.command: awk -F{{ ':' }} '$2 == "" {print$1}' /etc/shadow
  register: users_without_password
  changed_when: users_without_password.stdout != ""
  check_mode: false

- name: Gestionar usuarios sin contraseña
  ansible.builtin.include_tasks: usuarios_sin_contrasena_gestionar.yml
  when: users_without_password.changed
