---
- name: 619B_Reiniciar_audit
  ansible.builtin.include_tasks:
    file: handler_reglas_audit.yml

- name: 619B_Aplicar_cambios_parametros_gnome
  ansible.builtin.include_tasks:
    file: handler_parametros_gnome.yml

- name: 619B_Reiniciar_host
  throttle: 1
  become: true
  ansible.builtin.reboot:
    msg: "Reinicio lanzado por Ansible para aplicar políticas del ENS"
    pre_reboot_delay: 60
    post_reboot_delay: 60
    reboot_timeout: 300
    test_command: "{{ reboot_test_command | default('whoami') }}"
