---
- name: Reiniciar_servicio_audit
  become: true
  ansible.builtin.command: service auditd restart
  # COMENTARIO: Los módulos service y systemd no reiniciaban correctamente el servicio auditd, por lo que se usa el módulo command
  #  systemd:
  #  name: auditd
  #  state: restarted
  #  use: service
- name: Listar_reglas_audit
  block:
    - name: Obtener reglas audit
      become: true
      ansible.builtin.command: auditctl -l
      register: lista_reglas_audit
      changed_when: lista_reglas_audit.rc == 0
    - name: Mostrar lista de reglas de audit
      ansible.builtin.debug:
        var: lista_reglas_audit.stdout_lines
